### ISSUE TITLE
lxqt config-appereance  set to sddm

### ISSUE THREAD

**Issue by ringo32** [lxqt/lxqt-config#907] opened 2023-01-05 20:27 UTC
i am using arch based endeavouros  , after update of today appereance settings logsout to sddm

##### Current Behavior

when i start lxqt-config-appereance it logsout to sddm 

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* lxqt-build-tools Version: 
* Package version: 

https://0bin.net/paste/ef-hZK3Y#bcxfw7vSs5zPKmrV3MCT9y6fJcLxpgomU-Hv/H5f682

local/liblxqt 1.2.0-1

pacman log https://termbin.com/3kuh

**Comment by tsujan** [comment] 2023-01-05 20:50
Please do this and attach what comes after `where`:

1. `coredumpctl gdb lxqt-config-app` (or whatever the name is)
2. `where`

**Comment by tsujan** [comment] 2023-01-05 21:04
Never mind; your [link](https://0bin.net/paste/ef-hZK3Y#bcxfw7vSs5zPKmrV3MCT9y6fJcLxpgomU-Hv/H5f682) shows no problem specifically in `lxqt-config-appearance`. There may be something wrong with the builds or with the upgrade in your distro.

Closing, but you could add comments or more info to this page

**Comment by ringo32** [comment] 2023-01-05 21:04
when i do your coredumpctl i get https://termbin.com/ty61k

but

when i do
 [ringo@lxqt ~]$ coredumpctl gdb lxqt-config-appearance 
No match found.


it logs out to sddm ..

with adding the path  https://termbin.com/y2yz

**Closed by tsujan** 2023-01-05 21:04 UTC

**Comment by tsujan** [comment] 2023-01-05 21:14
What comes after `where` is more human-readable; otherwise, it's the same as your link: no specific line about `lxqt-config-appearance`, except that it started and crashed. It suggests that the cause is something else. My guess is either a bad/incompatible build or an incomplete distro upgrade.

**Comment by ringo32** [comment] 2023-01-06 15:47
i stil figuring command for where . but wil look further what it is ..

**Comment by ringo32** [comment] 2023-01-06 15:53
nevermind.. Removed LXQT config folder in .config , seems to be resolved.

**Comment by tsujan** [comment] 2023-01-06 16:05
lxqt-config doesn't have a folder. Its conf file is `~/.config/lxqt/lxqt-config.conf` and only contains the window size.

Which WM do you use? Openbox, KWin,...?

**Comment by tsujan** [comment] 2023-01-06 16:12
You could also check suspicious lines in `~/.local/share/sddm/xorg-session.log` (error, warning,…).

**Comment by tsujan** [comment] 2023-01-06 16:29
Oh, my mistake! You meant LXQt's config folder, namely `~/.config/lxqt/`.

If the session crash doesn't happen after its removal, the only things that come to my mind are an impossible WM like kwin_wayland or starting of two compositors alongside each other; otherwise, I don't think `lxqt-config-appereance` can cause a session crash by itself.

**Comment by tsujan** [comment] 2023-01-06 16:41
To be thorough, there's also a third possibility: Using a Qt style belonging to `qt5-styleplugins` after upgrading Qt. `qt5-styleplugins` should be recompiled after upgrading `qt5-base` (it's in AUR); otherwise, it might cause crashes in all Qt apps. It's better not to use it at all.

But I wonder whether a session crash is possible because of it. There's no trace of it in your backtrace either.

**Comment by stefonarch** [comment] 2023-01-06 17:40
The folder/file is gone at all now? Would be interesting trying reproduce with those settings.

**Comment by ringo32** [comment] 2023-01-06 19:27
i dont have qt5-styleplugins  only lightly-qt but not in use. i picked the config and packet had got only the wingmenu from menu in active 
[lxqt.tar.gz](https://github.com/lxqt/lxqt-config/files/10362547/lxqt.tar.gz)


dont have searched what it was actually

**Comment by stefonarch** [comment] 2023-01-06 20:41
I loaded the config in a debian VM. When opening `lxqt-config-appearance` the desktop freezes for about 10 sec and then session is crashing as descibed. Deleting ` lxqt-config-appearance.conf ` is enough to fix it. The screen size was huge:
```
[General]
ControlGTKThemeEnabled=true
__userfile__=true
size=@Size(32706 32673)
```

**Comment by ringo32** [comment] 2023-01-06 20:47
i dont know but wil try emulate the size was also after an update after all have to think i did resize te screen further no special i think have to play with it

**Comment by stefonarch** [comment] 2023-01-06 20:49
With 10k it still works, with 20k it freezes.

**Comment by ringo32** [comment] 2023-01-06 20:52
i have to review , my other ssd disk died on me had to reinstall te system found an old lxqt iso from a year old i made my own iso was pretty ugly too, but configured completly  can't recall direcly how it came...

**Comment by tsujan** [comment] 2023-01-06 20:55
> The screen size was huge:

Interesting! With which WM? (I'd asked this above.)

**Comment by stefonarch** [comment] 2023-01-06 20:57
Openbox, could test also with others.

**Comment by ringo32** [comment] 2023-01-06 21:04
aur packages are also picom-conf  sddm-conf  , havent played with other wm's yet with this install past install was i3wm xfwm4 but xfwm4 does not work nicely for me as keybindings of lxqt-panel taskbar .. dont know why it it become huge that way.
.

**Comment by tsujan** [comment] 2023-01-06 21:08
@stefonarch, thanks for your tests!

> With xfwm4 it's worse - it freezes

Wow! I thought WMs should handle such extreme situations.

Although this case is very rare, I think we should set the screen size as the upper limit wherever we save the window size. First we need a list of LXQt apps that save their window sizes — except for pcmanfm-qt, lximage-qt and LXQt file dialog, whose codes I'll check.

**Comment by stefonarch** [comment] 2023-01-06 21:13
I see only 3 files:` archiver.conf`, `lxqt-config.conf `and the one of this issue.

**Comment by tsujan** [comment] 2023-01-06 21:33
On second thought, since all saved sizes are actual window sizes, there's no need to clutter our codes by artificially setting upper limits.

Long story short, the config files are *correctly* created by their corresponding apps. If a user edits them manually, he/she will be responsible for the probable consequences.

**Comment by stefonarch** [comment] 2023-01-06 21:38
I wonder if it's possible by mouse moving or similar - it doesn't look edited, and it's hard to imagine  somebody editing those numbers. Or a saving failure?
BTW the apps are more:

```
 cat * |grep @Size
WindowSize=@Size(1846 931)
WindowSize=@Size(837 535)
WindowSize=@Size(969 556)
size=@Size(757 485)
size=@Size(1253 750)
size=@Size(794 496)
size=@Size(1012 714)

```

**Comment by tsujan** [comment] 2023-01-06 21:51
> I wonder if it's possible by mouse moving or similar

To a width of 32706? Theoretically possible, but it should be a wonderful mouse movement ;)

> Or a saving failure?

Qt doesn't save anything when an I/O failure happens. It uses a temporary file.

Anyway, it's not our job to prevent extremely rare mistakes.

**Comment by tsujan** [comment] 2023-10-11 11:39
> size=@Size(32767 32767)

Something should have resized the window to that enormous size; the app itself doesn't do it.

Also, IMHO, checking the screen size and limiting the window size to it in the code *each time a window is opened* — as a workaround for such cases — isn't an option.

> WM: Openbox

As Openbox's development stopped years ago, I suspect that this may be related to it. But that's just a wild guess.
