### ISSUE TITLE
Keyboard layout settings: /usr/share/X11/xkb/rules/base.extras.xml

### ISSUE THREAD

**Issue by Vovanium** [lxqt/lxqt-config#751] opened 2021-06-09 18:58 UTC
##### Expected Behavior
There's a file `/usr/share/X11/xkb/rules/base.extras.xml` (on Linux, other systems may have a different path) which contains some extra keyboard layouts in addition to those in `base.xml`. I want to have those extra layouts available in the Keyboard Layout Settings.

##### Current Behavior
Only `base.xml` is read, and only layouts from it are available.

##### Possible Solution
Read `base.extras.xml` in addition to `base.xml` on systems have that one.

##### Context
I'm using one of those keyboard layouts listed in `base.extra.xml`, and configuring it through Settings is not possible. It can be set through Settings Editor, but it is tricky.
I don't know if the mentioned file is available on all systems (I'm using Gentoo Linux), so it may require some work to keep the code cross-platform.

**Comment by tsujan** [comment] 2021-06-09 19:03
Duplicate of https://github.com/lxqt/lxqt-config/issues/748

**Closed by tsujan** 2021-06-09 19:03 UTC
