### ISSUE TITLE
Mouse settings have no effect (acceleration, sensivity)

### ISSUE THREAD

**Issue by agaida** [lxqt/lxqt-config#400] opened 2018-08-28 21:22 UTC
##### Expected Behavior

One should be able to set these parameters with our application

##### Current Behavior

one is not able to. xinput works fine

##### Possible Solution

fixing it

##### Steps to Reproduce (for bugs)

1. just play with the settings

##### System Information

* Distribution & Version: Debian Sid lxqt custom build

##### Remark

I'm able to set the matrix from the command line - so there is a chance to get this working
```
xinput list-props 14
Device 'Logitech M720 Triathlon':
        Device Enabled (154):   1
        Coordinate Transformation Matrix (156): 2.400000, 0.000000, 0.000000, 0.000000, 2.400000, 0.000000, 0.000000, 0.000000, 1.000000
        libinput Natural Scrolling Enabled (292):       0
        libinput Natural Scrolling Enabled Default (293):       0
        libinput Scroll Methods Available (294):        0, 0, 1
        libinput Scroll Method Enabled (295):   0, 0, 0
        libinput Scroll Method Enabled Default (296):   0, 0, 0
        libinput Button Scrolling Button (297): 2
        libinput Button Scrolling Button Default (298): 2
        libinput Middle Emulation Enabled (299):        0
        libinput Middle Emulation Enabled Default (300):        0
        libinput Accel Speed (301):     0.000000
        libinput Accel Speed Default (302):     0.000000
        libinput Accel Profiles Available (303):        1, 1
        libinput Accel Profile Enabled (304):   1, 0
        libinput Accel Profile Enabled Default (305):   1, 0
        libinput Left Handed Enabled (306):     0
        libinput Left Handed Enabled Default (307):     0
        libinput Send Events Modes Available (277):     1, 0
        libinput Send Events Mode Enabled (278):        0, 0
        libinput Send Events Mode Enabled Default (279):        0, 0
        Device Node (280):      "/dev/input/event5"
        Device Product ID (281):        1133, 16478
        libinput Drag Lock Buttons (308):       <no items>
        libinput Horizontal Scroll Enabled (309):       1

# insane fast
xinput set-prop 14  "Coordinate Transformation Matrix" 2.400000, 0.000000, 0.000000, 0.000000, 2.400000, 0.000000, 0.000000, 0.000000, 1.000000
# normal
xinput set-prop 14  "Coordinate Transformation Matrix" 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
# slow
xinput set-prop 14  "Coordinate Transformation Matrix" 0.500000, 0.000000, 0.000000, 0.000000, 0.500000, 0.000000, 0.000000, 0.000000, 1.000000
```

**Comment by tsujan** [comment] 2019-02-08 01:30
@agaida Please not before https://github.com/lxqt/lxqt-config/pull/394 is decided -- for the reason I told there.

**Comment by tsujan** [comment] 2019-05-30 00:09
The apply button patch was merged on Mar 25, 2019.

I think everyone agrees with @agaida that the GUI is confusing. The average user may not have a clue why the Mouse page has no effect on acceleration or sensitivity (the real mouse settings are under `Mouse and Touchpad` for most users). Not all users know that handling of input devices has changed in recent years.

Maybe we should add what's under `Motion` to `Mouse and Touchpad`. @yan12125 ?

**Comment by yan12125** [comment] 2019-05-30 05:13
Can't agree more. Settings covered by options in `Mouse and Touchpad` should be deprecated/removed, and others should be migrated from X11 Atoms to libinput.

**Comment by tsujan** [comment] 2019-05-30 09:58
> Settings covered by options in Mouse and Touchpad should be deprecated/removed

You mean in the `Mouse` section (the old settings).

OK, if I find time, I'll do it.

**Comment by yan12125** [comment] 2019-05-30 14:03
Yes!

No hurry. I think there is still some time before lxqt 0.15? @agaida

**Comment by tsujan** [comment] 2019-05-30 14:10
> I think there is still some time before lxqt 0.15

My internal LXQt timer says, "months".

**Comment by agaida** [comment] 2019-05-30 14:18
Maybe we should do a 0.14.x for some components before.

**Comment by tsujan** [comment] 2019-08-13 13:24
This group-box should be removed:

![old-settings](https://user-images.githubusercontent.com/981076/62945063-3aa36480-bdf3-11e9-8531-07e0b6c9eb72.png)

**Comment by tsujan** [comment] 2019-08-13 14:49
Before I make a PR... is this acceptable?

![new-settings](https://user-images.githubusercontent.com/981076/62951222-cff82600-bdfe-11e9-80ce-43a9ff414651.png)

What is done:

 1. The old settings are removed.
 2. "Mouse" is replaced by "Basic Mouse Settings".
 3. "Mouse and Touchpad" is the second item.
 4. The window and desktop file icon is changed to `preferences-desktop-peripherals`, as proposed at https://github.com/lxqt/lxqt-config/issues/524

**Comment by wxl** [comment] 2019-08-14 03:24
Excuse me if I'm jumping into the dumpster fire here, but why not just merge the two sections together?

**Comment by tsujan** [comment] 2019-08-14 03:39
> why not just merge the two sections together?

I had 3 reasons: They had different meanings (users' reason), "Mouse and Touchpad" had a different kind of code (programmers' reason), and I was afraid of a confusing GUI (programmers' fear of users). Otherwise, I have no problem with merging them together.

**Comment by wxl** [comment] 2019-08-14 03:41
I guess that "Basic Mouse Settings" doesn't come across as very meaningful. But I guess that's neither here nor there given the reasons you have stacked up to keep it the way you've suggested.

**Comment by tsujan** [comment] 2019-08-14 03:46
My reasons aren't important to me :) I just told what was in my head. I'll follow whatever decision taken here.

**Comment by tsujan** [comment] 2019-08-14 03:53
Actually, I came here because it was said there would be a release for Ubuntu. This is among those things that should be wrapped up. I also have 2 patches for QTerminal and lxqt-archiver. Then, as far as I am concerned, a new release will be OK.

**Comment by kassindornelles** [comment] 2020-04-26 06:32
im still waiting for a fix :)

**Comment by tsujan** [comment] 2020-04-26 06:37
This can be closed because the obsolete mouse settings are removed in 0.15.0. Mouse and touchpad settings are under "Mouse and Touchpad".

**Closed by tsujan** 2020-04-26 06:37 UTC

**Comment by Shellcat-Zero** [comment] 2020-09-18 12:57
@tsujan this is still an issue in 0.14.1, which is the current latest version available for Ubuntu 20.04 LTS.  Is this fix going to be backported to 0.14.1 or when should we expect 0.15.0 to be available in 20.04?

**Comment by tsujan** [comment] 2020-09-18 13:09
@Shellcat-Zero 
https://github.com/lxqt is where LXQt is being developed. Whether a distro provides its user with the latest release of LXQt or not is out of our control. Questions related to distros should be asked in their own bug trackers.

**Comment by motocyklista** [comment] 2021-05-04 21:59
I have this same problem with mouse settings in LXDE environment @tsujan you are also mentioned on section "People" in LXDE project. Do you know if LXDE is still active and who can fix it or to what person I should report it? Can you help? I will apreciate this. Or if you have contact to LXDE developer can you report this? Like I said no reaction for mouse sensitivity in acceleration in LXDE environment so it is the same bug like in LXQt.

**Comment by tsujan** [comment] 2021-05-05 02:24
> @tsujan you are also mentioned on section "People"

That's because of `libfm`. Years ago, it was used by LXQt, until `libfm-qt` was made. I'm not an LXDE developer/user.

**Comment by motocyklista** [comment] 2021-05-05 19:51
@tsujan so bug with mouse sensitivity was fixed on what release of LXQt? On 0.15.0 like was mentioned on this topic? On Lubuntu 20.04 bug still exist so it is why I asked about it. On LXDE also but like you mentioned this is separated project so we will not talking about it.

**Comment by tsujan** [comment] 2021-05-05 20:04
> so bug with mouse sensitivity was fixed 

Yes; otherwise, this page wouldn't be closed:

![new](https://user-images.githubusercontent.com/981076/117201564-04491c80-ae02-11eb-8ee2-5a51d6204d81.png)

> On Lubuntu 20.04 bug still exist

Lubuntu 20.0 has an outdated version of LXQt. The latest version is 0.17.

**Comment by motocyklista** [comment] 2021-05-05 21:06
@tsujan I will try this but I can see only acceleration speed settings but like we know acceleration and mouse sensitivity are two separate functions. How I can do changes for mouse sensitivity makes my mouse slower? I want to disable acceleration and makes sensitivity to low values. I don't like acceleration of mouse because when I was teenanger I played a lot of CS and I like have control of my mouse so this is very important aspect for me.

**Comment by tsujan** [comment] 2021-05-05 21:23
The "new" input device manager is called `libinput`. All distros have it. That's why old settings don't work.

`libinput` doesn't have the concept of "sensitivity". Some people play with its "coordinate transformation matrix" but that's tricky and has side effects. "Acceleration speed" should be enough for virtually all users. If not, `libinput` developers are responsible. However, I don't know of any report about "sensitivity" to `libinput`.

**Comment by motocyklista** [comment] 2021-05-05 21:45
@tsujan thank you for your answer and help. I used on other machine my Ubuntu 20.04 with GNOME environment and there mouse settings works perfectly so why you can't copy this solution? Of course I am not coder in this time. I want to learn programming so I have also second question. What language I should learn if I want to help you with this project? C# language or C++? Or maybe something other? Can you tell me?

**Comment by tsujan** [comment] 2021-05-05 22:58
> why you can't copy this solution?

Because we don't need it. What's important is `libinput`, not GNOME.

> What language I should learn if I want to help you with this project?

C++.

**Comment by motocyklista** [comment] 2021-05-06 10:39
@tsujan you have right about libinput. I changed configuration files for it and this also works on LXDE but I noticed that after this change my mouse it is not precise. I don't know if it caused by libinput or my mouse itself.
