### ISSUE TITLE
"Single click to activate items"

### ISSUE THREAD

**Issue by Bydo-Spore** [lxqt/lxqt-config#637] opened 2020-07-22 14:37 UTC
In 'Keyboard and Mouse Settings' -> 'Mouse and Touchpad', ticking "Single click to activate items" actually enables libinput tap-to-click behaviour.

This description is confusing, since "single click to activate items" is associated with opening directories in a file manager using a single click rather than a double click. Indeed, Thunar has an option with exactly this name that enables this behaviour.

It would make more sense if the option were labelled "Tap-to-click'.

**Comment by tsujan** [comment] 2020-07-22 14:46
It's clicking, not necessarily tapping. And file managers can override it in their preferences -- actually, all Qt apps can override it but usually don't.

**Comment by Bydo-Spore** [comment] 2020-07-22 15:03
No, it isn't clicking. What I said is correct. I have tested it. The option enables/disables tap-to-click. Whether that is intentional on your part is another matter. If not, I suggest you investigate the issue, rather than immediately and arrogantly dismissing and closing issues that were opened in ernest.

**Comment by tsujan** [comment] 2020-07-22 16:05
OK, I reopen this for further investigation.

@yan12125?

**Comment by tsujan** [comment] 2020-07-22 16:11
> ...rather than immediately and arrogantly dismissing....

There's no arrogance or dismissal in closing an issue. As I mentioned [elsewhere](https://github.com/lxqt/lxqt-config/issues/638#issuecomment-662542814), closed issues can be reopened. Please don't turn a report to an emotional conflict.

**Comment by Bydo-Spore** [comment] 2020-07-22 16:25
Thanks for reopening.
BTW, what seemed arrogant was that you immediately assumed I was wrong and consequently closed the issue without even checking whether what I said was correct.

How many other issues have been unjustly ignored in the past because of this rash and dismissive attitude?

**Comment by tsujan** [comment] 2020-07-22 16:37
> BTW, what seemed arrogant was that you immediately assumed I was wrong and consequently closed the issue without even checking whether what I said was correct.

I have no time to prove that it wasn't caused by my arrogance. These things happen. I was (am) very busy with coding for another part of LXQt; I also handle reports and try to keep them orderly. Sometimes good reports are closed and reopened again. I've closed and reopened my own reports too.

> How many other issues have been unjustly ignored

Quite conversely, there are many old reports that aren't valid anymore. We lack enough manpower.

**Comment by tsujan** [comment] 2020-07-22 19:35
Back to this:

As I suspected, "Single click to activate items" isn't related to enabling/disabling tapping. In the code, it sets `QPlatformTheme::ItemViewActivateItemOnSingleClick`, which is a Qt-only parameter. Moreover, `xinput list-props <id>` gives `libinput Tapping Enabled (309): 1` here, whether that box is checked or not.

@Bydo-Spore 
You didn't fill in the issue template. I don't know why it affects tapping in your case but, with the master branch, it doesn't.

Not reproducible; hence closing.

**Closed by tsujan** 2020-07-22 19:35 UTC

**Comment by yan12125** [comment] 2020-07-23 02:13
Maybe the options do interfere with each other (e.g., some daemon polls `ItemViewActivateItemOnSingleClick` and changes libinput knobs accordingly). However, as @tsujan said, without a properly filled issue template, we cannot investigate stuffs.
