### ISSUE TITLE
Shortcut for switching keyboard layout cannot be changed

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-config#445] opened 2019-03-22 15:18 UTC
I think that should be my fault; I should have missed it when adding the Apply button. (The same is true about changing keyboard model -- it has no effect.)

And it went into Debian stable :(

Will fix it as soon as possible.

**Comment by agaida** [comment] 2019-03-22 19:50
:) - shit happends - but we can consider it a regression that should be fixed before d/stable is released, can't we?

**Comment by tsujan** [comment] 2019-03-22 20:04
It'll be great if it can go into Debian stable. IMO, it was a big enough regression to need a point release only for `lxqt-config`.

Long story short, I tried to check everything before adding the Apply button but missed this one -- there were so many settings. It wasn't reported, perhaps, because the current LXQt users didn't need to change the shortcut but those who want to choose one for the first time have right to curse me ;)

**Comment by agaida** [comment] 2019-03-22 20:33
https://cdimage.debian.org/cdimage/weekly-live-builds/amd64/iso-hybrid/debian-live-testing-amd64-lxqt.iso
or
https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/weekly-live-builds/amd64/iso-hybrid/debian-live-testing-amd64-lxqt+nonfree.iso

**Comment by agaida** [comment] 2019-03-23 13:48
Hmm - i don't think that i can do a point release for stable, but i think i can apply the patch. Otherwise point release sounds good.

**Comment by tsujan** [comment] 2019-03-23 16:18
OK. It isn't a crashing bug after all; I may have dramatized it because I was surprised by it ;)

**Comment by agaida** [comment] 2019-03-23 16:20
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925352

I wouldn't care to much. I guess we will get the freeze exception - if not, who cares :D 

Might sound harsh, but i've planned for the buster release cycle the introduction of lxqt stable backports. So what.

**Comment by tsujan** [comment] 2019-03-23 16:32
You're right. I also remembered that KDE has much worse things now and then. As you said, "shit happens;" this one was small ;)

**Comment by agaida** [comment] 2019-03-23 16:35
and you should really start a debian live iso - looks nice for me.

**Comment by tsujan** [comment] 2019-03-23 16:40
There are 2 distros that I may not use anymore but I'm sure are very nice and can recommend to everyone: Debian and OpenSUSE :) Will try it with VirtualBox.

**Comment by agaida** [comment] 2019-03-23 16:53
I'm deeply relaxed when it comes to distributions. Ok, i have some favourites: Siduction of course, debian, archlinux - and i've been falled in love with rockstor (CentOS) for my NAS/Homeserver - ok, LXQt for Cent/RH could be more up to date, but it runs surprisingly fine as DE for a remote RDP desktop :)

**Comment by agaida** [comment] 2019-03-23 17:20
Fixed package unblocked for buster

**Comment by tsujan** [comment] 2019-03-23 17:52
:)

**Closed** 2019-03-24 19:12 UTC
Labels: bug

**Comment by sproclavism** [comment] 2019-07-06 12:14
Is there a temporary workaround for this? I cannot use the right alt key (which I use heavily) because of this bug, and the last release was back in February...

**Comment by tsujan** [comment] 2019-07-06 12:27
> I cannot use the right alt key (which I use heavily) because of this bug

Most distros already have the fix and it's in Debian Buster too. So, you'll have it soon.

**Comment by agaida** [comment] 2019-07-06 12:42
today to be precise - if one use debian

**Comment by sproclavism** [comment] 2019-07-06 13:07
Okay, thanks for the info guys

**Comment by agaida** [comment] 2019-07-06 13:11
not a joke - today is debian release day - so stay tuned. One will not get the latest and greatest LXQt directly from git, but our latest release with relevant backports and fixes. And to be honest: Yes, i love it, not only with my debian maintainer hat on.

**Comment by tsujan** [comment] 2019-07-06 13:18
> Yes, i love it

Me too. And it'll get better. LXQt has got a solid foundation, IMO.
