### ISSUE TITLE
[lxqt-config-monitor] Two "Apply" buttons in the same screen

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/lxqt-config#577] opened 2019-12-14 20:16 UTC
After opening lxqt-config-monitor, then selected "Paramètres" (Settings ) I get a list of saved configurations, and under the box, a first button "Appliquer" (Apply) and a second button "Appliquer" at the bottom right. Two buttons with the same name are confusing.
1. After selecting a config to restore, the second button has no effect. There is no need of a button which has no effect.
2. After a click on the second button, new settings are indeed applied, but the application is directly closed. In other parts of the application,like applying quick settings, we have a dialogue to confirm that the configuration is OK, and after that the application survives. I'm not in favour of to much dialogues, but I don't understand why this is dealt so differently.
Release Mageia lxqt-config-0.14.1-2.mga7

**Comment by the-loudspeaker** [comment] 2020-01-21 11:07
![2020-01-21-162750_1366x768_scrot](https://user-images.githubusercontent.com/37928641/72799637-b1c70980-3c6b-11ea-834c-5cedf706ee6f.png)

I think the op refers to the "Save" and "Apply" buttons. The thing is, they are for different purposes. "Apply" button only applies the setting to current session. The "Save" button makes it consistent across all sessions. Checkout the Settings dialoguebox to understand better. It is updated after you press the save button. The settings by "Apply" button do not remain after a reboot. 

I think it is good like this. acts as a failsafe.

**Comment by papoteur-mga** [comment] 2020-01-21 11:29
Hello,
I don't speak about this window, but this one, got when pressing on "Settings".
![image](https://user-images.githubusercontent.com/5154580/72801359-9fd46f00-3c49-11ea-8b99-0fac9713ea52.png)
You can that there is 2 "Apply" buttons.

**Comment by the-loudspeaker** [comment] 2020-01-21 17:46
Oh that! Sorry my bad. Will have to look in more.

**Comment by vc-01** [comment] 2023-04-06 09:15
I checked the [source](https://github.com/lxqt/lxqt-config/blob/c6a164b35a25c4e9b2600f7a1d36050f2a62c82d/lxqt-config-monitor/settingsdialog.cpp#L26) and indeed, the "Apply" button isn't connected to any action.

Neither, I see any default action for Apply button in _LXQt::ConfigDialog_ ([source](https://github.com/lxqt/liblxqt/blob/a0fafe2228b87271a9b9c6491cc3dfdd494ca752/configdialog/lxqtconfigdialog.cpp#L70)).

It feels good to click it, but it does nothing :)

I see the following options to fix the UI:

1. Keeping only the sub control "Apply" button

![image](https://user-images.githubusercontent.com/25567234/230326792-eb269fc4-8b23-4146-891d-47b3ce939436.png)

2. Keeping both "Apply" buttons doing the same. Once the dialog is expanded with more sub controls, the common "Apply" in the bottom will apply settings from all sub controls.

![image](https://user-images.githubusercontent.com/25567234/230327093-cc106b93-ee64-471b-a0f4-4dae4514d5f1.png)

3. Removing sub control "Apply" button and keeping only the common (dialog) "Apply" button

![image](https://user-images.githubusercontent.com/25567234/230327136-05da1433-b188-446c-b302-0ad27bf34b29.png)

For some reason, to me the first option feels the best, though it doesn't follow common approaches in UI which would be then option 2 or 3.

Once settled, I'm happy to make a PR.

**Comment by papoteur-mga** [comment] 2023-04-06 09:39
Thanks for the interest to this topic, opened ... ago. ;)
For option 1. I don't see the need to keep the "Close" button on a separate button box. All buttons could be in the same box.
Option 2 is a no sense, IMO.
Don't forget also my remark about the immediate closing after "Applying"

**Comment by vc-01** [comment] 2023-04-06 10:14
> For option 1. I don't see the need to keep the "Close" button on a separate button box. All buttons could be in the same box.

That would be a fourth option of getting rid of the sub control (or "Page" from _LXQt::ConfigDialog_ terminology) which I haven't looked into.

> Don't forget also my remark about the immediate closing after "Applying"

Firstly, I cannot reproduce it. And it is always better (or is it a rule?) to open separate issues for separate topics . I can stick only to the first half of this one - which is the UI part. This sounds to me like the application is crashing, not closing. And that would definitely require opening another issue if that's still (since 2019) the case (see again topic of this issue).

**Comment by papoteur-mga** [comment] 2023-10-15 13:56
I have just installed v1.3.0, but this issue is still valid.
Papoteur

**Comment by vc-01** [comment] 2023-10-16 21:50
I could possibly have time to implement one of the proposed fixes (but not fixing the bug, being the second part of this issue). Only I was waiting for any team member to approve it or propose some other change.

**Comment by papoteur-mga** [comment] 2023-10-17 06:27
If buttons can not be grouped on one line, I would prefer the option 3.

**Comment by vc-01** [comment] 2023-10-17 12:13
Yes, thank you for the opinion, but since what I was proposing is a _change_ to the UI - I was waiting for someone tagged "Member" to have a word on this. Not that the work requires too much time to implement but any time wasted is you know ... _wasted_.

**Comment by tsujan** [comment] 2023-10-22 17:31
Yes, that GUI definitely needs more love — its problems are more than what's mentioned here.

PRs are always welcome. It might take a while before devs find time to review them, and their reviews need active cooperation of the contributors.

**Comment by vc-01** [comment] 2023-10-24 11:29
@tsujan Thank you for reaction. I will blend together what's been discussed here in this thread, perhaps with a few other details and fixes. I will be reachable until the PR has been merged.

@papoteur-mga Thank you too for opening this issue and for any further reactions so, things can get moving.

**Comment by vc-01** [comment] 2023-10-29 08:19
> If buttons can not be grouped on one line ...

@papoteur-mga They surely can be grouped in any way, only aligning them on one line would break the concept of "Advanced settings" dialog having multiple so called "pages" in it, currently having only one, the "Saved Settings" page.

Question is whether there will ever be more pages in the dialog, but to propose a commit with the least possible breaking changes I will prepare one for the option 3. I'm bearing in mind that changing the layout breaks also translations.

**Comment by tsujan** [comment] 2023-11-15 15:51
The problems in main report have been fixed in https://github.com/lxqt/lxqt-config/commit/3005400ce273b117833a8043f03af39f7596101d.

It's preferable to open separate issues for the other problems, for contributors to make separate PRs for them.

**Closed by tsujan** 2023-11-15 15:51 UTC
